### ISSUE TITLE
path.yaml format maybe is wrong

### ISSUE THREAD

**Issue by jvech** [kiwicampus/Turtlebot-Gazebo-Navigator#3]
The file `path.yaml` on tb_bringup has the form:
```
points:
  position:
    x: 0.1
    y: 0.2
  position:
    x: 0.4
    y: 0.8
```

Which represents i guess a list of pose positions, but the standard yaml states that:
you must past a list of objects in the following form

```
points:
  - { position: {x: -1.9999998807907104, y: -0.39999985694885254 } }
  - { position: {x: -1.9715254540968772, y: -0.4179205420303447 } }
```
