### ISSUE TITLE
the low_level_pkg name is wrong

### ISSUE THREAD

**Issue by jvech** [kiwicampus/Turtlebot-Gazebo-Navigator#4]
on the file `configs/nodes_launch.yaml` the name for the `low_level_pkg` seems to be incorrect the file shows:
```yaml
NODE_LOW_LEVEL_COMMANDER:
  launch: 0
  node_executable: low_level_commander_node
  package: low_level_nav2_commander
  respawn: true
  respawn_delay: 5.0
```

but the package field should be

```yaml
NODE_LOW_LEVEL_COMMANDER:
  launch: 0
  node_executable: low_level_commander_node
  package: low_level_pkg
  respawn: true
  respawn_delay: 5.0
```
